Repository googleinterns/step217-2020, pull requests merged in 2020-09, with the labels that each got.

#39 Added Youtube component for YouTube Servlet
  src/main/webapp/src/components/songInfo.js
  src/main/webapp/src/components/youTubeRecommendations.js
Labels: deployed

#41 Synchronize all analysis components
  src/main/webapp/src/components/entityAnalysisInfo.js
  src/main/webapp/src/components/sentimentAnalysisInfo.js
  src/main/webapp/src/components/songInfo.js
  src/main/webapp/src/components/youTubeRecommendations.js
  src/main/webapp/src/helpers/objectEquals.js
Labels: deployed

#48 Chart is now clickable
  src/main/webapp/src/components/entityAnalysisInfo.js
Labels: deployed

#52 Display top song info
  src/main/java/com/google/alpollo/AnalysisInfoServlet.java
  src/main/java/com/google/alpollo/SongDataBase.java
  src/main/java/com/google/alpollo/model/AnalysisInfo.java
  src/main/java/com/google/alpollo/model/SongCounter.java
  src/main/webapp/package.json
  src/main/webapp/src/app.js
  src/main/webapp/src/components/entityAnalysisInfo.js
  src/main/webapp/src/components/ratingList.js
  src/main/webapp/src/components/sentimentAnalysisInfo.js
  src/main/webapp/src/components/songInfo.js
  src/main/webapp/src/components/youTubeRecommendations.js
Labels: deployed

#54 Display interpretation of sentiment analysis
  src/main/java/com/google/alpollo/model/AnalysisInfo.java
  src/main/webapp/src/components/sentimentAnalysisInfo.js
  src/main/webapp/src/components/songInfo.js
Labels: deployed

#60 Format salience
  src/main/webapp/src/components/entityAnalysisInfo.js
Labels: important

#62 Set charset of responses to utf-8
  src/main/java/com/google/alpollo/servlets/AnalysisInfoServlet.java
  src/main/java/com/google/alpollo/servlets/SentimentServlet.java
  src/main/java/com/google/alpollo/servlets/TopSongsServlet.java
  src/main/java/com/google/alpollo/servlets/YouTubeServlet.java
Labels: important

#57 Text to speech
  pom.xml
  src/main/java/com/google/alpollo/helpers/DetectLanguageService.java
  src/main/java/com/google/alpollo/helpers/TextToSpeechService.java
  src/main/java/com/google/alpollo/servlets/AnalysisInfoServlet.java
  src/main/java/com/google/alpollo/servlets/SentimentServlet.java
  src/main/java/com/google/alpollo/servlets/TextToSpeechServlet.java
  src/main/java/com/google/alpollo/servlets/TopSongsServlet.java
  src/main/java/com/google/alpollo/servlets/YouTubeServlet.java
  src/main/webapp/package.json
  src/main/webapp/src/components/lyrics.js
  src/test/java/com/google/alpollo/AnalysisTest.java
Labels: deployed, important

#58 Autocomplete artist and song name
  pom.xml
  src/main/java/com/google/alpollo/servlets/AutocompleteServlet.java
  src/test/java/com/google/alpollo/AnalysisTest.java
Labels: important

#59 Add autocomplete field for artist name
  src/main/java/com/google/alpollo/model/AutocompleteSearchRequest.java
  src/main/java/com/google/alpollo/servlets/AutocompleteServlet.java
  src/main/webapp/package.json
  src/main/webapp/src/components/autocompleteTextField.js
  src/main/webapp/src/components/search.js
  src/test/java/com/google/alpollo/AnalysisTest.java
Labels: deployed, important
